### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by theRealScoobaSteve**
Adding documentation for branching off a branch

### CODE REVIEW

**Comment by theRealScoobaSteve** [comment]
@JakeGreer @jaylevin @CoreyRo

**Comment by theRealScoobaSteve** [comment]
@JakeGreer @JakeGreer

**Comment by theRealScoobaSteve** [comment]
Fixes

**Review by jaylevin — APPROVED** [review]

**Comment by theRealScoobaSteve** [comment]
Fixed #49

**Pull request merged**
